#!/bin/sh

# npm NEEDS node and node-waf, since modules installation scripts usually call them.
PATH=/usr/lib/npm/bin:$PATH

if [ "0" = $(id -u) ]; then
	# root install, global paths
	export npm_config_globalconfig=/etc/npm/rootrc
else
	# user install
	export npm_config_globalconfig=/etc/npm/userrc
fi

# run it
nodejs /usr/share/npm/npm.js $@
